---
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Set default policy to deny incoming traffic
  ufw:
    direction: incoming
    policy: deny

- name: Allow SSH (port 22)
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow HTTP (port 80)
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
