# nginx-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
      <head><title>DevOps Course</title></head>
      <body><h1>Hello from EKS + NGINX</h1></body>
    </html>
