version: "3.9"

services:
  web:
    image: nginx:latest
    volumes:
      - ./web-data:/usr/share/nginx/html
    # ports:
    #   - "8080:80"
    networks:
      - appnet

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:latest
    networks:
      - appnet

volumes:
  db-data:

networks:
  appnet:
